version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fruit-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: fruitdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fruit-network

  fruit-app:
    build: .
    container_name: fruit-api-mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:mongopass@mongodb:27017/fruitdb?authSource=admin
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
    networks:
      - fruit-network

volumes:
  mongodb_data:

networks:
  fruit-network:
    driver: bridge